name: DRsocial
favicon: null
layout_spectrum: 0.9148907749913633
typography_spectrum: 0.7596910623833537
title: TSO
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.05824009305797517
  lightness: 0.2036573647055775
  saturation: 0.19938472285866737
  rhythmicContrast: 0.1692444949876517
purpose: []
